### ISSUE TITLE
 Usage Examples

### ISSUE THREAD

**Issue by KSVQ** [douggrubba/laravel-4-haversine-model#1]
Are there any use examples for this available? Use with laravel 4.2?

**Comment by douggrubba** [comment]
Wow, sorry about that.  Wrote this back in 3 and this totally doesn't work in 4

I've pushed a fix that should take care of any issues.

You should be able to extend this class with one of your models and then would be able to something like this.

```
$locations = $myModel->closest('35.2269', '80.8433', 250);
```

This would probably make a good trait as well.  If I get some time next week maybe I can add that in.

Also, if you could always just add this method to your model or base model.

Please let me know if you have any other questions.

_Doug_

**Comment by KSVQ** [comment]
Thanks Doug :) I appreciate the response. I'll play with it and post feedback. Looks good by the way.

**Comment by riyan119** [comment]
how i can implement in laravel 5 sir?

**Comment by douggrubba** [comment]
It would probably be really similar just a few syntax changes in the query builder:

https://laravel.com/docs/5.5/queries

I'm not quite up to date on the differences between the query builder in 4 vs. 5 but it shouldn't be too different.
